### ISSUE TITLE
lib0/logging is missing from lib0@0.2.70

### ISSUE THREAD

**Issue by JanMisker** [yjs/yjs#511]
When I just run `npm update` I get errors, because it seems `lib0/logging` is missing.
```
Failed to resolve 'lib0/logging' from 'node_modules/yjs/dist/yjs.mjs'
```

When I pin lib0 to 0.2.69 with `npm i lib0@0.2.69` everything works fine.

**Comment by dmonad** [comment]
Thanks! This should be fixed now in `lib0@0.2.72`.

**Comment by JanMisker** [comment]
@dmonad it's still broken for me :(

I use yjs inside my own library that's then used as a package for my app, maybe that's what triggers this? Perhaps creating a yjs release with the latest lib0 requested?

If I run `npm i lib0@0.2.69` my application builds, but if I run `npm i lib0@0.2.72` or `npm i lib0@latest` it doesn't...

**Comment by dmonad** [comment]
Hi @JanMisker,

I updated lib0 in Yjs and published `yjs@13.5.51`. Could you check again?

**Comment by JanMisker** [comment]
Hi @dmonad I check but it still fails. However I had a closer look at what's exactly installed in `node_modules/lib0/` and noticed that there is no `logging.js`, only `logging.browser.js`, `logging.commons.js` or `logging.node.js`. I guess that's the problem, no `logging.js` for the `import ... from 'logging'` to resolve? 

In 0.2.72 it looks like this:
<img width="219" alt="lib0@0 2 72" src="https://user-images.githubusercontent.com/334008/226873087-d624aac4-4386-41e6-a7d1-285e2687ef87.png">


Whereas in 0.2.69 like this:
<img width="191" alt="lib0@0 2 69" src="https://user-images.githubusercontent.com/334008/226873107-94b49769-3c60-4bc3-a015-17cf2c3a7409.png">

**Comment by JanMisker** [comment]
Yes I updated to `yjs@13.5.51` but I indeed use a bundler (Parcel) that probably doesn't recognise it properly... I also have a `npm link` situation going on while developing locally which might also play into this issue.

I'm not a bundler expert... any suggestions where to look for a solution?

**Comment by dmonad** [comment]
Parcel should be able to work with Yjs@13.5.51. `logging.js` is no longer requested. I recommend deleting `node_modules` and maybe `package-lock.json` as well. Make sure that everything in `package.json` is fine. Then install again: `npm i`.

**Comment by JanMisker** [comment]
@dmonad yeah I tried all that, also `npm ci`.
It keeps complaining about not finding `lib0/logging`

I created a repository showcasing the minimal example 
https://github.com/JanMisker/yjs-test

<img width="699" alt="image" src="https://user-images.githubusercontent.com/334008/226910161-a4c3d235-3199-4cdb-b8e6-dbb6e28b3640.png">
